[package]
name = "project_one"
version = "0.1.0"
authors = ["Dima <di.vo.se@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9.3"